In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
X = df.drop('species',axis=1)
y = df['species']

In [ ]:
label = LabelEncoder()
y_enc = label.fit_transform(y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_enc, test_size=0.20, random_state=42, stratify=y)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_Knn = KNeighborsClassifier(n_neighbors= 13)

In [ ]:
model_Knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_Knn.score(X_test,y_test)

0.9666666666666667

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_Svm = SVC(gamma='auto')

In [ ]:
model_Svm.fit(X_train,y_train)

SVC(gamma='auto')

In [ ]:
model_Svm.score(X_test,y_test)

0.9666666666666667

Now lets use the **GridSearchCV**

GridSearchCV is a Scikit-learn technique that systematically tests different combinations of hyperparameters using cross-validation and selects the combination that performs best according to a chosen evaluation metric.

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV((model_Svm),{
    'C' : [1,10,20,30],
    'kernel' : ['linear','rbf']
},cv=5)

In [ ]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['linear', 'rbf']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00398207, 0.00294266, 0.00250731, 0.00287576, 0.00260849,
        0.00268574, 0.00242434, 0.00241413]),
 'std_fit_time': array([7.00048122e-04, 2.59421002e-04, 1.81103393e-04, 2.17736159e-04,
        2.71089763e-04, 2.08141763e-04, 1.06032502e-04, 7.27325330e-05]),
 'mean_score_time': array([0.00266891, 0.00225325, 0.00192904, 0.0021399 , 0.00184565,
        0.00211058, 0.00188894, 0.00178576]),
 'std_score_time': array([2.30904198e-04, 3.17739159e-04, 1.45763980e-04, 1.48582765e-04,
        6.37114759e-05, 1.46276869e-04, 1.44308793e-04, 6.52603523e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'}],
 'split0_test_score': array([0.96666667, 0.96666667, 1.        , 0.96666667, 1.        ,
        0.96666667, 1.        , 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.9       , 0.96666667, 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.9       , 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.97333333, 0.98      , 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.03887301, 0.01632993, 0.0421637 ,
        0.03651484, 0.04898979, 0.03887301]),
 'rank_test_score': array([1, 1, 4, 1, 6, 5, 7, 7], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)

In [ ]:
results

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.003982      0.000700  ...        0.016330                1
1       0.002943      0.000259  ...        0.016330                1
2       0.002507      0.000181  ...        0.038873                4
3       0.002876      0.000218  ...        0.016330                1
4       0.002608      0.000271  ...        0.042164                6
5       0.002686      0.000208  ...        0.036515                5
6       0.002424      0.000106  ...        0.048990                7
7       0.002414      0.000073  ...        0.038873                7

[8 rows x 15 columns]

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1          rbf         0.980000
2       10       linear         0.973333
3       10          rbf         0.980000
4       20       linear         0.966667
5       20          rbf         0.966667
6       30       linear         0.960000
7       30          rbf         0.960000

Now lets use the **RandomSearchCV**

RandomizedSearchCV is a Scikit-learn technique that randomly samples a specified number of hyperparameter combinations and evaluates them using cross-validation to identify a good-performing configuration.

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r = RandomizedSearchCV((model_Svm),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear']
},n_iter=4,cv=5,return_train_score=False)

In [ ]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
results_r = pd.DataFrame(classifier_r.cv_results_)

In [ ]:
results_r

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.005603      0.001163  ...        0.036515                3
1       0.004230      0.000466  ...        0.038873                2
2       0.004377      0.000189  ...        0.038873                4
3       0.004204      0.000510  ...        0.016330                1

[4 rows x 15 columns]

In [ ]:
results_r[['param_kernel','param_C','mean_test_score']]

  param_kernel  param_C  mean_test_score
0          rbf       20         0.966667
1       linear       10         0.973333
2          rbf       30         0.960000
3       linear        1         0.980000

**Ensemble Learning** :              
Ensemble Learning is a machine learning technique in which multiple models work together to make a prediction, often producing better results than an individual model.

Imagine you're trying to predict whether a passenger survived the Titanic disaster.

You train three different models:

Model 1: Logistic Regression predicts that the passenger survived.
Model 2: Decision Tree predicts that the passenger did not survive.
Model 3: Random Forest predicts that the passenger survived.

If you combine their predictions using majority voting, the final prediction is:

Survived.

Two out of three models predicted survival.

**Types of Ensemble Learning** :

Bagging — Bootstrap Aggregating.

Boosting — Sequentially improving predictive performance.

Stacking — Combining predictions using a meta-model.

**Stacking (Stacked Generalization)**
Stacking is an ensemble technique in which the predictions of multiple base models become inputs to a second-level model called a meta-model.

In [ ]:
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [ ]:
base_models = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc',SVC(probability=True, kernel='rbf', random_state=42)),
    ('lr', LogisticRegression(max_iter=1000))
]

In [ ]:
meta_model = LogisticRegression(max_iter=1000)

In [ ]:
stacking_clf = StackingClassifier(
    estimators=base_models,
    final_estimator=meta_model,
    cv=5
)

In [ ]:
stacking_clf.fit(X_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [ ]:
y_pred = stacking_clf.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.9666666666666667

**Bagging (Bootstrap Aggregating)**

Bagging is an ensemble technique in which multiple models are trained independently on different bootstrap samples of the training data, and their predictions are combined.

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_model = RandomForestClassifier(
    n_estimators=100,   #number of Trees
    max_depth = None,
    random_state=42,
    max_features="sqrt"
)

In [ ]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = rf_model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.9

**Boosting**

Boosting is an ensemble technique in which models are trained sequentially, with later models designed to improve the ensemble's performance.

**AdaBoost Adaptive Boosting, Gradient Boosting, XGBoost**

In [ ]:
from sklearn.ensemble import AdaBoostClassifier , GradientBoostingClassifier
from xgboost import XGBClassifier

In [ ]:
ada_model = AdaBoostClassifier(n_estimators=100, learning_rate=1.0, random_state=None)

In [ ]:
ada_model.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=100)

In [ ]:
y_pred = ada_model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.9333333333333333

In [ ]:
gradient_model = GradientBoostingClassifier(loss='log_loss', learning_rate=0.1, n_estimators=100, max_depth=3)

In [ ]:
gradient_model.fit(X_train,y_train)

GradientBoostingClassifier()

In [ ]:
y_pred = gradient_model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.9666666666666667

In [ ]:
xg_model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, use_label_encoder=False, eval_matric='mlogloss',random_state=42)

In [ ]:
xg_model.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [15:41:24] WARNING: /__w/xgboost/xgboost/src/learner.cc:794:
Parameters: { "eval_matric", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_matric='mlogloss', eval_metric=None,
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None, ...)

In [ ]:
y_pred = xg_model.predict(X_test)

In [ ]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.9333333333333333